//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalNote
{
    using System;
    using System.Collections.Generic;
    
    public partial class anagrafica
    {
        public int id { get; set; }
        public string ragionesociale { get; set; }
        public string nome { get; set; }
        public string cognome { get; set; }
        public string indirizzo { get; set; }
        public string Cap { get; set; }
        public string citta { get; set; }
        public string provincia { get; set; }
        public string Telefono { get; set; }
        public string Cellulare { get; set; }
        public string email { get; set; }
        public int idUtente { get; set; }
    }
}
