//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalNote
{
    using System;
    using System.Collections.Generic;
    
    public partial class cause_doc
    {
        public int idcause_doc { get; set; }
        public int idcausa { get; set; }
        public string filename { get; set; }
        public string filetype { get; set; }
    }
}
