//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalNote
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class legalnoteEntities : DbContext
    {
        public legalnoteEntities()
            : base("name=legalnoteEntities")
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<anagrafica> anagrafica { get; set; }
        public virtual DbSet<cause> cause { get; set; }
        public virtual DbSet<cause_doc> cause_doc { get; set; }
        public virtual DbSet<utenti> utenti { get; set; }
    }
    public partial class legalnoteEntities : DbContext
    {
        public legalnoteEntities(string connectionString) : base(connectionString)
        {
        }
    }
}
